Repository AY2425S1-CS2103T-F15-4/tp, pull requests merged in 2024-10, with the labels that each got.

#35 Change instances of Wedding Planner Pro to WedLinker
  docs/_markbind/layouts/default.md
  docs/site.json
  docs/team/riccoljy.md
Labels: severity.Medium

#38 Update UI mockup and README
  docs/images/Ui.png
  docs/index.md
Labels: priority.High

#37 Update developer guide (User Stories & Glossary)
  docs/DeveloperGuide.md
Labels: priority.High

#4 Add `FilterCommand`, `FilterCommandParser`, `FilterCommandTest`
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
Labels: priority.High

#64 Add support for `Untag` feature
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/UntagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UntagCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/UntagCommandTest.java
  src/test/java/seedu/address/logic/parser/UntagCommandParserTest.java
Labels: priority.High

#129 Update UG to reflect v1.4
  docs/UserGuide.md
  docs/images/findAlexDavidResult.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task

#141 Add Find Command UML Diagram
  docs/diagrams/FindCommandClass.puml
Labels: priority.High

#170 Update User Guide
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findCommandName.png
  docs/images/findCommandTag.png
  docs/images/findCommandWedding.png
  docs/images/helpMessage.png
  docs/images/release.png
Labels: type.Task
